# Source: sd-core/charts/omec-sub-provision/templates/service-simapp.yaml
apiVersion: v1
kind: Service
metadata: # kpt-merge: omec/simapp
  name: simapp
  labels:
    release: sd-core
    app: simapp
  namespace: omec
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|omec|simapp'
spec:
  type: ClusterIP
  selector:
    release: sd-core
    app: simapp
  ports:
  - name: prometheus-exporter
    port: 9089
    protocol: TCP
  - name: config-exporter
    port: 8080
    protocol: TCP
