# Source: sd-core/charts/omec-user-plane/templates/service-upf.yaml
apiVersion: v1
kind: Service
metadata: # kpt-merge: omec/upf
  name: upf
  labels:
    release: sd-core
    app: upf
  namespace: omec
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|omec|upf'
spec:
  type: ClusterIP
  selector:
    release: sd-core
    app: upf
  ports:
  - name: pfcp
    protocol: UDP
    port: 8805
