# Source: sd-core/charts/5g-control-plane/templates/deployment-udr.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: omec/udr
  name: udr
  namespace: omec
  labels:
    release: sd-core
    app: udr
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|RoleBinding|omec|udr'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: udr
subjects:
- kind: ServiceAccount
  name: udr
  namespace: omec
