# Source: sd-core/charts/5g-control-plane/templates/deployment-amf.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: omec/amf
  name: amf
  namespace: omec
  labels:
    release: sd-core
    app: amf
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|RoleBinding|omec|amf'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: amf
subjects:
- kind: ServiceAccount
  name: amf
  namespace: omec
