# Source: sd-core/charts/5g-control-plane/templates/deployment-nrf.yaml
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: omec/nrf
  name: nrf
  namespace: omec
  labels:
    release: sd-core
    app: nrf
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|omec|nrf'
