# Source: sd-core/charts/5g-control-plane/templates/deployment-udr.yaml
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: omec/udr
  name: udr
  namespace: omec
  labels:
    release: sd-core
    app: udr
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|omec|udr'
