# Source: sd-core/charts/omec-sub-provision/templates/deployment-simapp.yaml
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: omec/simapp
  name: simapp
  namespace: omec
  labels:
    release: sd-core
    app: simapp
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|omec|simapp'
