# Source: sd-core/charts/5g-control-plane/templates/deployment-webui.yaml
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: omec/webui
  name: webui
  namespace: omec
  labels:
    release: sd-core
    app: webui
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|omec|webui'
