# Source: sd-core/charts/5g-control-plane/templates/deployment-nssf.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: default/nssf
  name: nssf
  namespace: default
  labels:
    release: sd-core
    app: nssf
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|RoleBinding|default|nssf'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nssf
subjects:
- kind: ServiceAccount
  name: nssf
  namespace: default
