# Source: sd-core/charts/5g-control-plane/templates/deployment-webui.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: default/webui
  name: webui
  namespace: default
  labels:
    release: sd-core
    app: webui
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|RoleBinding|default|webui'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webui
subjects:
- kind: ServiceAccount
  name: webui
  namespace: default
