# Source: sd-core/charts/5g-control-plane/charts/mongodb/templates/replicaset/headless-svc.yaml
apiVersion: v1
kind: Service
metadata: # kpt-merge: default/mongodb-headless
  name: mongodb-headless
  namespace: default
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.31.5
    app.kubernetes.io/instance: sd-core
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|mongodb-headless'
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: sd-core
    app.kubernetes.io/component: mongodb
