apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: # kpt-merge: default/subscriber-proxy-secret-reader
  name: subscriber-proxy-secret-reader
  namespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRoleBinding|default|subscriber-proxy-secret-reader'
subjects:
- kind: ServiceAccount
  name: subscriber-proxy
  namespace: default
roleRef:
  kind: ClusterRole
  name: subscriber-proxy-secret-reader-role
  apiGroup: rbac.authorization.k8s.io
