{
 "title": "Cluster Health",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Nodes Status",
   "type": "timeseries",
   "description": "Cluster Availability",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (node) (kube_node_status_condition{condition=~\"Ready\",status=~\"true\"})",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}
{
 "title": "E2E Tests",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "agents",
    "label": "Agents",
    "query": {
     "query": "label_values(aetheredge_e2e_tests_ok, name)"
    }
   },
   { "name": "ds", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Monitoring agents E2E Test",
   "type": "timeseries",
   "description": "E2E Tests",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (name) (aetheredge_e2e_tests_ok{name=~\"$agents\"})",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}
{
 "title": "ENB Status",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "enb",
    "label": "ENB",
    "query": {
     "query": "label_values(mme_number_of_enb_attached, enbname)"
    }
   },
   { "name": "ds", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Site Small Cells connectivity status",
   "type": "timeseries",
   "description": "Small Cells connectivity on MME",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (enbname) (mme_number_of_enb_attached{enb_state=\"Active\", enbname=~\"$enb\"})",
     "legendFormat": "{{enbname}}"
    }
   ]
  }
 ]
}
{
 "title": "UE Connectivity",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "imsi",
    "label": "IMSI",
    "query": {
     "query": "label_values(subscribers_info, imsi)"
    }
   },
   { "name": "ds", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "UE $imsi Connectivity",
   "type": "timeseries",
   "description": "UE Connectivity",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (imsi) (subscribers_info{imsi=\"$imsi\"})",
     "legendFormat": "IMSI {{imsi}}"
    }
   ]
  }
 ]
}