kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata: # kpt-merge: default/onos-config
  name: onos-config
  namespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|RoleBinding|default|onos-config'
subjects:
- kind: ServiceAccount
  name: onos-config
roleRef:
  kind: Role
  name: onos-config
  apiGroup: rbac.authorization.k8s.io
