kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata: # kpt-merge: default/onos-topo
  name: onos-topo
  namespace: aether-roc
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|RoleBinding|default|onos-topo'
subjects:
- kind: ServiceAccount
  name: onos-topo
roleRef:
  kind: Role
  name: onos-topo
  apiGroup: rbac.authorization.k8s.io
