apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: # kpt-merge: default/onos-topo
  creationTimestamp: null
  name: onos-topo
  namespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|Role|default|onos-topo'
rules:
- apiGroups:
  - primitives.atomix.io
  resources:
  - '*'
  resourceNames:
  - onos-topo-objects
  verbs:
  - '*'
