apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: default/aether-roc-gui-v2-1-access-services
  name: aether-roc-gui-v2-1-access-services
  namespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|RoleBinding|default|aether-roc-gui-v2-1-access-services'
subjects:
- kind: ServiceAccount
  name: default # Name is case sensitive
  namespace: default
roleRef:
  kind: Role
  name: aether-roc-gui-v2-1-service-role
  apiGroup: rbac.authorization.k8s.io
