# Source: aether-roc-umbrella/charts/prometheus-acc/templates/server/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: default/aether-roc-umbrella-prometheus-acc-server
  labels:
    component: "server"
    app: prometheus-acc
    release: aether-roc-umbrella
    chart: prometheus-acc-14.6.1
    heritage: Helm
  name: aether-roc-umbrella-prometheus-acc-server
  namespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|default|aether-roc-umbrella-prometheus-acc-server'
