# Source: aether-roc-umbrella/charts/prometheus-ace/charts/kube-state-metrics/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: default/aether-roc-umbrella-kube-state-metrics
  labels:
    app.kubernetes.io/name: kube-state-metrics
    helm.sh/chart: kube-state-metrics-3.4.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: aether-roc-umbrella
  name: aether-roc-umbrella-kube-state-metrics
  namespace: aether-roc
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|default|aether-roc-umbrella-kube-state-metrics'
imagePullSecrets: []
