# Source: aether-roc-umbrella/charts/sdcore-test-dummy/templates/svc.yaml
apiVersion: v1
kind: Service
metadata: # kpt-merge: default/aether-roc-umbrella-sdcore-test-dummy
  name: aether-roc-umbrella-sdcore-test-dummy
  namespace: "default"
  labels:
    app.kubernetes.io/name: sdcore-test-dummy
    helm.sh/chart: sdcore-test-dummy-12.0.0
    app.kubernetes.io/instance: aether-roc-umbrella
    app.kubernetes.io/managed-by: Helm
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|aether-roc-umbrella-sdcore-test-dummy'
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/name: sdcore-test-dummy
    app.kubernetes.io/instance: aether-roc-umbrella
