# Source: aether-roc-umbrella/templates/store.yaml
# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: atomix.io/v2beta1
kind: Store
metadata: # kpt-merge: default/onos-consensus-store
  name: onos-consensus-store
  namespace: aether-roc
  annotations:
    internal.kpt.dev/upstream-identifier: 'atomix.io|Store|default|onos-consensus-store'
spec:
  protocol:
    apiVersion: storage.atomix.io/v2beta2
    kind: MultiRaftProtocol
    spec:
      replicas: 1
      groups: 1
      image: ""
      imagePullPolicy: IfNotPresent
