# Source: aether-roc-umbrella/charts/prometheus-acc/templates/server/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: # kpt-merge: /aether-roc-umbrella-prometheus-acc-server
  labels:
    component: "server"
    app: prometheus-acc
    release: aether-roc-umbrella
    chart: prometheus-acc-14.6.1
    heritage: Helm
  name: aether-roc-umbrella-prometheus-acc-server
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRole|default|aether-roc-umbrella-prometheus-acc-server'
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  - ingresses
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "extensions"
  - "networking.k8s.io"
  resources:
  - ingresses/status
  - ingresses
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
