# Source: aether-roc-umbrella/charts/prometheus-ace/templates/server/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: # kpt-merge: /aether-roc-umbrella-prometheus-ace-server
  labels:
    component: "server"
    app: prometheus-ace
    release: aether-roc-umbrella
    chart: prometheus-ace-14.6.1
    heritage: Helm
  name: aether-roc-umbrella-prometheus-ace-server
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRoleBinding|default|aether-roc-umbrella-prometheus-ace-server'
subjects:
- kind: ServiceAccount
  name: aether-roc-umbrella-prometheus-ace-server
  namespace: aether-roc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aether-roc-umbrella-prometheus-ace-server
