# Source: aether-roc-umbrella/charts/grafana/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata: # kpt-merge: /aether-roc-umbrella-grafana-clusterrole
  labels:
    helm.sh/chart: grafana-6.16.6
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: aether-roc-umbrella
    app.kubernetes.io/version: "8.1.2"
    app.kubernetes.io/managed-by: Helm
  name: aether-roc-umbrella-grafana-clusterrole
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRole|default|aether-roc-umbrella-grafana-clusterrole'
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]
