apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /sdcore-adapter-v2-1-logconfig
  name: sdcore-adapter-v2-1-logconfig
  labels:
    app: sdcore-adapter-v2-1
    chart: "sdcore-adapter-v2-1-2.1.3"
    release: "aether-roc-umbrella"
    heritage: "Helm"
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|sdcore-adapter-v2-1-logconfig'
  namespace: aether-roc
data:
  logging.yaml: |-
    loggers:
      root:
        level: info
        output:
          stdout:
            sink: stdout
    sinks:
      stdout:
        stdout: {}
        type: stdout
