apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /onos-topo-config
  name: onos-topo-config
  labels:
    app: onos-topo
    chart: "onos-topo-1.3.5"
    release: "aether-roc-umbrella"
    heritage: "Helm"
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|onos-topo-config'
  namespace: aether-roc
data:
  onos.yaml: ""
  logging.yaml: |2-

    loggers:
      root:
        level: info
        output:
          stdout:
            sink: stdout
    sinks:
      stdout:
        stdout: {}
        type: stdout
