# Source: aether-roc-umbrella/templates/topo.yaml
# The 4G/5G v2.0.0 sdcore-adapter
apiVersion: topo.onosproject.org/v1beta1
kind: Entity
metadata: # kpt-merge: /connectivity-service-v2
  name: connectivity-service-v2
  annotations:
    internal.kpt.dev/upstream-identifier: 'topo.onosproject.org|Entity|default|connectivity-service-v2'
spec:
  uri: connectivity-service-v2
  kind:
    name: aether
  aspects:
    onos.topo.Configurable:
      address: sdcore-adapter-v2-0:5150
      version: 2.0.x
      type: aether
    onos.topo.Location:
      lat: 52.5150
      lng: 13.3885
    onos.topo.TLSOptions:
      insecure: true
    onos.topo.Asset:
      name: 5G Core
    onos.topo.MastershipState: {}
