# Source: sd-core/charts/5g-control-plane/templates/deployment-ausf.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: default/ausf
  name: ausf
  namespace: default
  labels:
    release: sd-core
    app: ausf
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|RoleBinding|default|ausf'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ausf
subjects:
- kind: ServiceAccount
  name: ausf
  namespace: default
