# Source: sd-core/charts/5g-control-plane/templates/deployment-udm.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: # kpt-merge: default/udm
  name: udm
  namespace: default
  labels:
    release: sd-core
    app: udm
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|Role|default|udm'
rules:
- apiGroups:
  - ""
  - extensions
  - batch
  - apps
  verbs:
  - get
  - list
  - patch
  resources:
  - statefulsets
  - daemonsets
  - jobs
  - pods
  - services
  - endpoints
  - configmaps
