# Source: sd-core/charts/5g-control-plane/templates/deployment-udm.yaml
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: default/udm
  name: udm
  namespace: omec
  labels:
    release: sd-core
    app: udm
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|default|udm'
