# Source: sd-core/charts/5g-control-plane/templates/deployment-ausf.yaml
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: default/ausf
  name: ausf
  namespace: omec
  labels:
    release: sd-core
    app: ausf
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|default|ausf'
