# Source: sd-core/charts/5g-control-plane/templates/deployment-amf.yaml
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: default/amf
  name: amf
  namespace: omec
  labels:
    release: sd-core
    app: amf
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|default|amf'
