kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata: # kpt-merge: /onos-operator-topo
  name: onos-operator-topo
  labels:
    app: onos-operator-topo
    chart: "topo-operator-0.5.4"
    release: "onos-operator"
    heritage: "Helm"
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRoleBinding|default|onos-operator-topo'
subjects:
- kind: ServiceAccount
  name: onos-operator-topo
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: onos-operator-topo
  apiGroup: rbac.authorization.k8s.io
