apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /onos-operator-topo-config
  name: onos-operator-topo-config
  labels:
    app: onos-operator-topo
    chart: "topo-operator-0.5.4"
    release: "onos-operator"
    heritage: "Helm"
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|onos-operator-topo-config'
data:
  logging.yaml: |-
    loggers:
      root:
        level: info
        output:
          stdout:
            sink: stdout
    sinks:
      stdout:
        stdout: {}
        type: stdout
