# Source: atomix-controller/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata: # kpt-merge: /atomix-controller
  name: atomix-controller
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRoleBinding|default|atomix-controller'
subjects:
- kind: ServiceAccount
  name: atomix-controller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: atomix-controller
  apiGroup: rbac.authorization.k8s.io
