# Source: atomix-controller/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /atomix-controller-config
  name: atomix-controller-config
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|atomix-controller-config'
data:
  logging.yaml: |-
    loggers:
      root:
        level: debug
        output:
          stdout:
            sink: stdout
    sinks:
      stdout:
        type: stdout
        stdout: {}
