# Source: sd-core/charts/5g-control-plane/templates/service-nssf.yaml
apiVersion: v1
kind: Service
metadata: # kpt-merge: /nssf
  name: nssf
  labels:
    release: sd-core
    app: nssf
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|nssf'
spec:
  type: ClusterIP
  selector:
    release: sd-core
    app: nssf
  ports:
  - name: sbi
    port: 29531
    protocol: TCP
