# Source: atomix-raft-storage/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata: # kpt-merge: /atomix-raft-storage-controller
  name: atomix-raft-storage-controller
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRoleBinding|default|atomix-raft-storage-controller'
subjects:
- kind: ServiceAccount
  name: atomix-raft-storage-controller
  namespace: default
roleRef:
  kind: ClusterRole
  name: atomix-raft-storage-controller
  apiGroup: rbac.authorization.k8s.io
